version: '2'
services:
  api:
    build: .
    ports:
      - '8080:8080'
    environment:
      VIRTUAL_HOST: 'killa.dev'
    labels:
      - lb.hook=true
    volumes:
      - ./src:/usr/local/killa/src
    command: nodemon -L /usr/local/killa/src/server.js

networks:
  default:
    external:
      name: KillaNetwork